import type { Metadata } from "next";
import "./globals.css";
import {Inter} from "next/font/google"
import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";


const inter= Inter({ subsets: ["latin"]});


export const metadata: Metadata = {
  title: "MyPortfolio",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: {locale:string};
}>) {
  const messages= await getMessages({locale: params.locale});
  return (
    <html lang={params.locale}>
      <body className={inter.className}>
        <NextIntlClientProvider messages={messages}>
        {children}
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
